# Generated by Django 3.1.2 on 2020-10-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20201010_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='number',
            field=models.IntegerField(default=0, verbose_name='№'),
        ),
        migrations.AddField(
            model_name='entry',
            name='number_out',
            field=models.CharField(default=0, max_length=64, verbose_name='№ исх.'),
        ),
    ]
