# Generated by Django 3.1.2 on 2020-10-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_auto_20201010_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='body',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='title',
        ),
        migrations.AddField(
            model_name='entry',
            name='executor',
            field=models.CharField(default='', max_length=200, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='entry',
            name='to_whom',
            field=models.CharField(default='', max_length=200, verbose_name='Кому'),
        ),
        migrations.AddField(
            model_name='entry',
            name='what',
            field=models.CharField(default='', max_length=200, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_time',
            field=models.DateTimeField(verbose_name='Дата и время регистрации'),
        ),
    ]
