# Generated by Django 3.1.2 on 2020-10-20 12:27

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_auto_20201010_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_time',
        ),
        migrations.AddField(
            model_name='entry',
            name='reg_date',
            field=models.DateField(default=datetime.date.today(), verbose_name='Дата регистрации документа'),
        ),
        migrations.AddField(
            model_name='entry',
            name='reg_time',
            field=models.TimeField(default=datetime.datetime.now().time(), verbose_name='Время регистрации документа'),
        ),
    ]
