# Generated by Django 3.1.2 on 2021-03-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_auto_20210118_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='document_index',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='reg_date',
            field=models.DateField(auto_now=True, verbose_name='Дата регистрации'),
        ),
    ]
