# Generated by Django 3.1.2 on 2021-03-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20210317_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='document_index',
            field=models.CharField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default='06', max_length=200),
        ),
    ]
