# Generated by Django 3.1.2 on 2021-03-18 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_auto_20210317_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='document_index',
        ),
    ]
