# Generated by Django 3.1.2 on 2021-03-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_remove_entry_document_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='user_ip',
            field=models.GenericIPAddressField(default=0, verbose_name='IP адрес'),
        ),
    ]
