# Generated by Django 3.1.2 on 2021-03-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_entry_user_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='reg_time',
            field=models.TimeField(auto_now=True, verbose_name='Время регистрации'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='user_ip',
            field=models.GenericIPAddressField(default='не определён', verbose_name='IP адрес'),
        ),
    ]
