# Generated by Django 3.1.2 on 2021-03-18 13:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20210318_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
