# Generated by Django 3.1.2 on 2021-03-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_entry_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='text',
        ),
    ]
