# Generated by Django 3.1.2 on 2021-09-06 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0016_remove_entry_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='№')),
                ('reg_date', models.DateField(blank=True, editable=False, verbose_name='Дата регистрации')),
                ('reg_time', models.TimeField(blank=True, editable=False, verbose_name='Время регистрации')),
                ('number_out', models.CharField(default='', max_length=64, verbose_name='№ исх.')),
                ('to_whom', models.CharField(default='', max_length=200, verbose_name='Кому')),
                ('what', models.CharField(default='', max_length=200, verbose_name='Содержание')),
                ('executor', models.CharField(default='', max_length=200, verbose_name='Исполнитель')),
                ('departament', models.CharField(default='', max_length=200, verbose_name='Отдел')),
                ('user_ip', models.GenericIPAddressField(default='не определён', verbose_name='IP адрес')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Запись в журнале',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
