# Generated by Django 3.1.2 on 2021-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0002_auto_20211109_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='data',
            field=models.JSONField(verbose_name='Изменяемые данные модели'),
        ),
    ]
