# Generated by Django 3.1.2 on 2021-11-09 12:53

import changelog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0003_auto_20211109_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='data',
            field=models.JSONField(decoder=changelog.utils.ReadableJSONFormField, verbose_name='Изменяемые данные модели'),
        ),
    ]
