# Generated by Django 3.1.2 on 2021-11-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0005_auto_20211109_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='data',
            field=models.TextField(verbose_name='Изменяемые данные модели'),
        ),
    ]
