# Generated by Django 3.1.2 on 2021-11-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0006_auto_20211110_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='data',
        ),
        migrations.AddField(
            model_name='changelog',
            name='after',
            field=models.TextField(default=None, verbose_name='Данные после изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changelog',
            name='before',
            field=models.TextField(default=1, verbose_name='Данные до изменения'),
            preserve_default=False,
        ),
    ]
