# Generated by Django 3.1.2 on 2021-04-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='reports',
            name='doc',
            field=models.CharField(default='', max_length=64, verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='reports',
            name='doc_number',
            field=models.CharField(default='', max_length=64, verbose_name='№ документа'),
        ),
        migrations.AddField(
            model_name='reports',
            name='from_to',
            field=models.CharField(default='', max_length=64, verbose_name='От кого/кому'),
        ),
        migrations.AddField(
            model_name='reports',
            name='what',
            field=models.CharField(default='', max_length=200, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='reports',
            name='сomment',
            field=models.CharField(default='', max_length=200, verbose_name='Примечание'),
        ),
    ]
