# Generated by Django 3.1.2 on 2021-04-08 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report_journal', '0002_auto_20210408_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='сomment',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='reports',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
