# Generated by Django 3.1.2 on 2021-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_journal', '0003_auto_20210408_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='date',
            field=models.DateField(blank=True, default='не указана', null=True, verbose_name='Дата'),
        ),
    ]
