# Generated by Django 3.1.2 on 2021-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_journal', '0004_auto_20210408_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Примечание'),
        ),
    ]
