# Generated by Django 3.1.2 on 2021-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_journal', '0005_auto_20210408_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='number',
            field=models.CharField(blank=True, default='б/н', max_length=300, verbose_name='№'),
        ),
    ]
