# Generated by Django 3.1.2 on 2021-01-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='number',
            field=models.IntegerField(default=0, verbose_name='№'),
        ),
    ]
