# Generated by Django 3.1.2 on 2021-01-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20210118_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='executor',
        ),
    ]
