# Generated by Django 3.1.2 on 2021-01-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_full_name',
            field=models.CharField(default='', max_length=200, verbose_name='Полное название договора'),
        ),
        migrations.AddField(
            model_name='contract',
            name='departament_code',
            field=models.IntegerField(default=0, verbose_name='Код отдела'),
        ),
    ]
