# Generated by Django 3.1.2 on 2021-01-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20210119_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(default='', max_length=3, verbose_name='№'),
        ),
    ]
