# Generated by Django 3.1.2 on 2021-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20210119_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_index',
            field=models.CharField(default='', max_length=3, verbose_name='Индекс'),
        ),
    ]
