# Generated by Django 3.1.2 on 2021-01-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20210122_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='registration_date',
            field=models.DateField(auto_now=True),
        ),
    ]
