# Generated by Django 3.1.2 on 2021-01-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_auto_20210122_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(default='', upload_to='documents/contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
