# Generated by Django 3.1.2 on 2021-02-04 10:43

import contracts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_auto_20210127_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заключения договора'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, default='', storage=contracts.models.OverwriteStorage(), upload_to=contracts.models.upload_to),
        ),
    ]
