# Generated by Django 3.1.2 on 2021-02-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_auto_20210204_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(default='', max_length=300, verbose_name='№'),
        ),
    ]
