# Generated by Django 3.1.2 on 2021-02-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_auto_20210217_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_agent',
            field=models.CharField(default='', max_length=200, verbose_name='Контрагент:'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_index',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Индекс'),
        ),
    ]
